# 再利用可能な「Slint on Zephyr アプリ」の土台.
# アプリ側 CMakeLists の使い方:
#   set(SLINT_DIR <clone した Slint>)
#   include(${SLINT_DIR}/demos/zephyr-common/slint-zephyr-app.cmake)
#   slint_zephyr_conf()                         # find_package の前に
#   find_package(Zephyr)
#   project(<名前> LANGUAGES CXX)
#   slint_zephyr_app(../ui/xxx.slint main.cpp)  # project の後に
if(NOT DEFINED SLINT_DIR)
    message(FATAL_ERROR "SLINT_DIR に clone した Slint の場所を指定してください")
endif()
set(SLINT_ZEPHYR_COMMON ${SLINT_DIR}/demos/zephyr-common)

# find_package(Zephyr) の前に呼ぶ. 共有 + このアプリの conf/overlay を積む.
macro(slint_zephyr_conf)
    if(NOT BOARD)
        message(FATAL_ERROR "No BOARD option specified")
    endif()
    string(REGEX REPLACE "@[^/]*" "" BOARD_CONF_NAME "${BOARD}")
    string(REPLACE "/" "_" BOARD_CONF_NAME "${BOARD_CONF_NAME}")
    set(CONF_FILE ${SLINT_ZEPHYR_COMMON}/prj.conf)
    set(EXTRA_CONF_FILE "")
    set(DTC_OVERLAY_FILE "")
    # アプリの prj.conf は共有の prj.conf の上に積む (普通の Zephyr アプリと同じ場所).
    if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/prj.conf)
        list(APPEND EXTRA_CONF_FILE ${CMAKE_CURRENT_SOURCE_DIR}/prj.conf)
    endif()
    # SLINT_ZEPHYR_* の knob はここの Kconfig が定義する. アプリが自前の Kconfig を
    # 持つときは, そちらで source "${SLINT_ZEPHYR_COMMON}/Kconfig" する.
    if(NOT EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/Kconfig)
        set(KCONFIG_ROOT ${SLINT_ZEPHYR_COMMON}/Kconfig)
    endif()
    foreach(dir ${SLINT_ZEPHYR_COMMON} ${CMAKE_CURRENT_SOURCE_DIR})
        if(EXISTS ${dir}/boards/${BOARD_CONF_NAME}.conf)
            list(APPEND EXTRA_CONF_FILE ${dir}/boards/${BOARD_CONF_NAME}.conf)
        endif()
        if(EXISTS ${dir}/boards/${BOARD_CONF_NAME}.overlay)
            list(APPEND DTC_OVERLAY_FILE ${dir}/boards/${BOARD_CONF_NAME}.overlay)
        endif()
    endforeach()
    # pwm-servo はこのリポジトリ独自の binding なので在り処を教える.
    list(APPEND DTS_ROOT ${SLINT_ZEPHYR_COMMON})
endmacro()

# project() の後に呼ぶ. Rust の target を選び, Slint と画面まわりを app に足す.
function(slint_zephyr_app ui)
    if(CONFIG_XTENSA)
        set(Rust_TOOLCHAIN "esp")
        set(Rust_CARGO_TARGET "xtensa-esp32-none-elf")
    elseif(CONFIG_ARCH_POSIX)
        set(Rust_CARGO_TARGET "x86_64-unknown-linux-gnu")
    elseif(CONFIG_ARM64)
        set(Rust_CARGO_TARGET "aarch64-unknown-none")
    elseif(CONFIG_CPU_CORTEX_M)
        if(CONFIG_CPU_CORTEX_M0 OR CONFIG_CPU_CORTEX_M0PLUS OR CONFIG_CPU_CORTEX_M1)
            set(Rust_CARGO_TARGET "thumbv6m-none-eabi")
        elseif(CONFIG_CPU_CORTEX_M23)
            set(Rust_CARGO_TARGET "thumbv8m.base-none-eabi")
        elseif(CONFIG_CPU_CORTEX_M33 OR CONFIG_CPU_CORTEX_M55 OR CONFIG_CPU_CORTEX_M85)
            set(Rust_CARGO_TARGET "thumbv8m.main-none-eabi")
        elseif(CONFIG_CPU_CORTEX_M4 OR CONFIG_CPU_CORTEX_M7)
            set(Rust_CARGO_TARGET "thumbv7em-none-eabi")
        else()
            set(Rust_CARGO_TARGET "thumbv7m-none-eabi")
        endif()
        if(CONFIG_FP_HARDABI AND Rust_CARGO_TARGET MATCHES "thumbv[78]")
            string(APPEND Rust_CARGO_TARGET "hf")
        endif()
    elseif(CONFIG_CPU_CORTEX_A OR CONFIG_CPU_CORTEX_R)
        set(Rust_CARGO_TARGET "armv7a-none-eabi")
    else()
        message(FATAL_ERROR "Rust target が分からない CPU: ${BOARD}")
    endif()
    # core/alloc の pre-built が無い target はその場で組む (nightly が要る).
    if(Rust_CARGO_TARGET MATCHES "^(xtensa|aarch64-unknown-none|armv7a)" OR CONFIG_ARCH_POSIX)
        set(SLINT_LIBRARY_CARGO_FLAGS "-Zbuild-std=core,alloc")
    endif()
    set(SLINT_FEATURE_FREESTANDING ON)
    set(SLINT_FEATURE_RENDERER_SOFTWARE ON)
    set(DEFAULT_SLINT_EMBED_RESOURCES "embed-for-software-renderer" CACHE STRING "")
    set(CMAKE_BUILD_TYPE Release)
    set(BUILD_SHARED_LIBS OFF)
    set(Rust_CARGO_TARGET_LINK_NATIVE_LIBS "" CACHE INTERNAL "" FORCE)
    add_subdirectory(${SLINT_DIR} slint_build)

    target_sources(app PRIVATE ${SLINT_ZEPHYR_COMMON}/slint-zephyr.cpp
                   ${SLINT_ZEPHYR_COMMON}/spiram_heap.c ${ARGN})
    target_include_directories(app PRIVATE ${SLINT_ZEPHYR_COMMON})
    target_link_libraries(app PRIVATE Slint::Slint)
    if(CONFIG_SLINT_ZEPHYR_RGB565_NATIVE_ENDIAN)
        target_compile_definitions(app PRIVATE SLINT_ZEPHYR_RGB565_NATIVE_ENDIAN)
    endif()
    foreach(part Y:%Y M:%m D:%d H:%H MIN:%M S:%S)
        string(REPLACE ":" ";" part "${part}")
        list(GET part 0 name)
        list(GET part 1 fmt)
        string(TIMESTAMP value "${fmt}")
        string(REGEX REPLACE "^0+([0-9])" "\\1" value "${value}")
        target_compile_definitions(app PRIVATE CARPARK_BUILD_${name}=${value})
    endforeach()
    if(CONFIG_SLINT_ZEPHYR_SCALE_FACTOR)
        set_property(TARGET app PROPERTY SLINT_SCALE_FACTOR ${CONFIG_SLINT_ZEPHYR_SCALE_FACTOR})
        target_compile_definitions(app PRIVATE
            SLINT_ZEPHYR_SCALE_FACTOR=${CONFIG_SLINT_ZEPHYR_SCALE_FACTOR})
    endif()
    slint_target_sources(app ${ui})
endfunction()
